### ISSUE TITLE
Repo select list not selecting correct repo to clone

### ISSUE THREAD

**Issue by ryanavogel** [InsiteSoftware/beacon#2]
**Reproduction steps:**

1. From the main menu, select the "clone client" option (#2).
2. Scroll down to the "huskyb2becomm" repo.
3. Press enter.

**Expected:** Clones the huskyb2becomm repo into c:\Projects\Clients\huskyb2becomm directory.
**Actual:** Clones a seemingly random repo. This is just a guess, but I don't think cloning a repo past the "first page" on the select list works. It seems to clone a repo only from the "first page" and which one it clones depends on how far past the "first page" you scroll.

As a side note, this is not a permissions issue because I can clone the huskyb2becomm repo outside of beacon.

![image](https://user-images.githubusercontent.com/17071837/111635984-0f9aa700-87c6-11eb-96fb-927b9ba4dcf2.png)

**Comment by belav** [comment]
as a workaround, if you type "husky" the list gets filtered down, and you don't have to scroll down to a new page.
